# XSS Vibes V2 - Advanced Crawler Configuration

# Fofa API Configuration
fofa:
  email: "" # Your Fofa email
  key: "" # Your Fofa API key
  enabled: false

# Shodan API Configuration
shodan:
  api_key: "" # Your Shodan API key
  enabled: false

# Crawling Configuration
crawling:
  max_depth: 5
  delay: 0.5 # Delay between requests (seconds)
  timeout: 30 # Request timeout (seconds)
  threads: 50 # Concurrent crawling threads
  user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

# Nuclei Configuration
nuclei:
  templates_path: "~/nuclei-templates/"
  severity: "critical,high,medium,low,info"
  threads: 100
  timeout: "2h"

# Jaeles Configuration
jaeles:
  signatures: "~/.jaeles/base-signatures/"
  threads: 50
  timeout: "1h"

# Output Configuration
output:
  directory: "output"
  format: ["json", "html", "txt"]

# Advanced Options
advanced:
  # Custom headers for requests
  headers:
    X-Forwarded-For: "127.0.0.1"
    X-Real-IP: "127.0.0.1"

  # File extensions to crawl
  extensions:
    - php
    - asp
    - aspx
    - jsp
    - do
    - action
    - json
    - xml
    - js

  # Exclude patterns
  exclude_patterns:
    - ".*\\.css$"
    - ".*\\.jpg$"
    - ".*\\.png$"
    - ".*\\.gif$"
    - ".*\\.pdf$"
    - ".*\\.zip$"

  # Keywords for endpoint discovery
  api_keywords:
    - "/api/"
    - "/rest/"
    - "/v1/"
    - "/v2/"
    - "/v3/"
    - "/graphql"
    - "/ajax/"
    - "/json/"
    - "/xml/"
    - "/admin/"
    - "/panel/"
    - "/dashboard/"

# Fofa Query Examples
fofa_queries:
  web_apps: 'title="login" || title="admin" || title="dashboard"'
  php_apps: 'body="php" && country="US"'
  vulnerable: 'title="phpMyAdmin" || title="WordPress" || title="Joomla"'
  apis: 'body="/api/" || body="/rest/" || body="graphql"'

# Shodan Query Examples
shodan_queries:
  web_servers: "http.title:login port:80,443"
  php_servers: "http.component:php port:80,443"
  cms_systems: "http.title:wordpress OR http.title:joomla OR http.title:drupal"
  api_endpoints: "http.html:/api/ port:80,443"
